menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/naituw
    GitHub: https://github.com/Naituw

favicon: /favicon.png
logo: /favicon.png

# Comment
# e.g disqus: seansun
disqus:
duoshuo:

# Analytics
# google-analytics:

# Copyright Infomation
startyear: 2018
